development:
  adapter: async

  # Permitir conexiones desde cualquier dominio (para ngrok)
  allowed_request_origins:
    - http://localhost:3000
    - http://127.0.0.1:3000
    - <%= ENV['NGROK_URL'] %>


test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: backend_production
